#!/usr/bin/env bash
# redirection - The direction must be a 301 Moved permanently

if [ ! -e "/usr/sbin/nginx" ]; then
	apt-get update
	apt-get -y install nginx
fi
FILE_PATH=/var/www/html
printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root   $FILE_PATH;
	index  index.html index.htm;

	location /redirect_me {
		return 301 https://youtube.com/;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
