#!/usr/bin/env bash
# install haproxy and configures it
# Replace "STUDENT_ID" with your actual student ID
STUDENT_ID="246453"

# Update the system and install HAProxy
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get update
apt-get -y install haproxy=2.8.\*

echo "ENABLED-1" >> /etc/default/haproxy
# Backup the default HAProxy configuration file
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Create a new HAProxy configuration file
tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log 127.0.0.1 local0 notice
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats

    default_backend http_back

backend http_back
    balance roundrobin
    server ${STUDENT_ID}-web-01 100.25.10.250:80 check
    server ${STUDENT_ID}-web-02 100.25.155.18:80 check
EOL

# Restart HAProxy to apply the changes
sudo service start haproxy

# Enable HAProxy to start on boot
sudo service enable haproxy

