#!/usr/bin/env bash
# install haproxy and configures it
# Replace "STUDENT_ID" with your actual student ID

# Update the system and install HAProxy
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get update
apt-get install haproxy=2.8.\*

# Backup the default HAProxy configuration file
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Create a new HAProxy configuration file
tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
defaults
    mode    http
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    timeout http-request  50000

frontend front_server
    bind :80
    default_backend back_server

backend back_server
    balance roundrobin
    server 246453-web-01 100.25.10.250:80 check
    server 246453-web-02 100.25.155.18:80 check
EOL

# Restart HAProxy to apply the changes
systemctl enable haproxy
systemctl restart haproxy

