#!/bin/bash

if [ "$EUID" -ne 0 ]; then
    echo "Please run this script with sudo:"
    echo "sudo $0"
    exit 1
fi

hosts_file="/etc/hosts"
localhost_entry="127.0.0.2 localhost"

# Backup the current hosts file
cp "$hosts_file" "$hosts_file.bak"

# Update hosts file with the specified localhost configuration
sed -i "/^127.0.0.1/s/^127.0.0.1.*/$localhost_entry/" "$hosts_file"

echo "Hosts file updated successfully:"
cat "$hosts_file"

