#!/usr/bin/env bash
# resolve host name to IP

hosts_file="/etc/hosts"
localhost_entry="127.0.0.2 localhost"
facebook_entry="8.8.8.8 facebook.com"

# Backup the current hosts file
cp "$hosts_file" "$hosts_file.bak"

# Update hosts file with the specified localhost configuration
if grep -q "^127.0.0.1" "$hosts_file.bak"; then
	sed -i "/^127.0.0.1/s/^127.0.0.1.*/$localhost_entry/" "$hosts_file.bak"
else
	echo "$localhost_entry" >> "$hosts_file.bak"
fi
if grep -q "facebook.com" "$hosts_file.bak"; then
	sed -i "s/.*facebook.com/$facebook_entry/" "$hosts_file.bak"
else
	echo "$facebook_entry" >> "$hosts_file.bak"
fi

cp "$hosts_file.bak" "$hosts_file"

